#!/usr/bin/env bash

# Colors
NOCOLOR='\033[0m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[32m'
BOLD='\033[1m'

# Configure .env and docker-compose files
function proceed_with_WP_environment() {

    # user-input - WordPress backend URL
    read -p "$(echo -e $BOLD"✍️  What is your WordPress URL? (defaults to http://localhost:8080): "$NOCOLOR)" WP_backend_url
    [ -z "$WP_backend_url" ] && echo -e $YELLOW"⚠️  Using default WordPress URL"$NOCOLOR && WP_backend_url="http://localhost:8080"
    check_url_input $WP_backend_url
    echo "NEXT_PUBLIC_WORDPRESS_SITE_URL=$WP_backend_url" > frontend/.env

    # Get port from url and update it in docker-compose file
    WP_backend_url_port="$(echo $WP_backend_url | sed -e 's,^.*:,:,g' -e 's,.*:\([0-9]*\).*,\1,g' -e 's,[^0-9],,g')"

    # If no port in URL then use port 80
    if [[ $WP_backend_url_port == "" ]]
    then
        sed -i -e "s/8080\:80/80:80/g" backend/docker-compose.yml
    else
        sed -i -e "s/8080\:80/$WP_backend_url_port\:80/g" backend/docker-compose.yml
    fi

    echo ""

    # user-input - Next.js frontend URL
    read -p "$(echo -e $BOLD"✍️  What is your Next.js frontend URL? (defaults to http://localhost:3000): "$NOCOLOR)" NextJS_frontend_url
    [ -z $NextJS_frontend_url ] && echo -e $YELLOW"⚠️  Using default Next.js frontend URL"$NOCOLOR && NextJS_frontend_url="http://localhost:3000"
    check_url_input $NextJS_frontend_url
    echo "NEXT_PUBLIC_NEXTJS_SITE_URL=$NextJS_frontend_url" >> frontend/.env

    echo ""
    echo -e $GREEN$BOLD"✅ Successfully created frontend/.env file"$NOCOLOR
}

# Start docker containers for the WordPress backend
function start_env_backend() {

    echo -e $BOLD"📦 Starting backend containers"$NOCOLOR
    docker-compose -f backend/docker-compose.yml up -d

    echo ""
}

# Run the Next.js development server
function start_env_frontend() {

    echo -e $BOLD "💻 Running frontend environment"$NOCOLOR
    npm i --prefix frontend/
    npm run dev --prefix frontend/
}

# Check URL
function check_url_input() {
    regex='(http?)://[-A-Za-z0-9:0-9]'
    user_input=$1

    if ! [[ $user_input =~ $regex ]]
    then
        echo -e $RED"🛑 URL is not valid."$NOCOLOR
        echo -e $RED"Please provide a url in the format: http://example.com:8080"$NOCOLOR
        exit
    fi
}

# Configure option
function configure() {
    # Ask user for preferred WordPress environment
    read -p "$(echo -e $BOLD"Would you like to use this project's WordPress backend setup? (n to use your own WordPress setup) [y/n]: "$NOCOLOR)" already_have_WP_environment

    case $already_have_WP_environment in
        [yY]* ) proceed_with_WP_environment;;
        [nN]* ) proceed_with_WP_environment;;
        * ) echo -e $RED"🛑 Please answer yes or no."$NOCOLOR && exit ;;
    esac
    if [[ "$already_have_WP_environment" == "y" ]] || [[ $already_have_WP_environment == "Y" ]]
    then
        start_env_backend && start_env_frontend
    else
        start_env_frontend
    fi
}

# Stop the running docker containers and remove them
function docker_container_stop() {

    echo -e $BOLD"📦 Stopping backend containers"$NOCOLOR
    docker-compose -f backend/docker-compose.yml down
}

# Help commands
function command_help() {

    echo "Please pass an argument"
    echo "Arguments: [ configure | start-all | start-backend | start-frontend | stop ]"
    echo ""
    echo "configure       Run the configuration wizard to set up the backend, frontend and create an .env file."
    echo "start-all       Create and start the docker environment for WordPress and run the Next.js development server."
    echo "start-backend   Create and start the docker environment for WordPress."
    echo "start-frontend  Run Next.js development server."
    echo "stop            Stop the docker environment for WordPress."
}

# Main function
# Checks command line arguments
function main() {

    case $1 in
        "configure" ) configure ;;
        "start-backend" ) start_env_backend ;;
        "start-frontend" ) start_env_frontend ;;
        "start-all" ) start_env_backend && start_env_frontend ;;
        "stop" ) docker_container_stop ;;
        * ) command_help ;;
    esac
}

main $1