name: DIGITALOCEAN_DEPLOY

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Change permissions
        run: echo ${{ secrets.DEPLOY_USER_PASSWORD }} | sudo -S chown -R $USER:$USER /home/github/actions-runner/_work/byob-headless-wordpress

      - uses: actions/checkout@main
      - name: Create .env
        working-directory: ./backend
        run: |
          echo 'MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}' >> .env
          echo 'MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}' >> .env
          echo 'MYSQL_USER=${{ secrets.MYSQL_USER }}' >> .env
          echo 'MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}' >> .env
          echo 'PMA_HOST=${{ secrets.PMA_HOST }}' >> .env
          echo 'PMA_PORT=${{ secrets.PMA_PORT }}' >> .env
          echo 'PMA_ARBITRARY=${{ secrets.PMA_ARBITRARY }}' >> .env
          echo 'WORDPRESS_DB_HOST=${{ secrets.WORDPRESS_DB_HOST }}' >> .env
          echo 'WORDPRESS_DB_NAME=${{ secrets.WORDPRESS_DB_NAME }}' >> .env
          echo 'WORDPRESS_DB_USER=${{ secrets.WORDPRESS_DB_USER }}' >> .env
          echo 'WORDPRESS_DB_PASSWORD=${{ secrets.WORDPRESS_DB_PASSWORD }}' >> .env
          echo 'WORDPRESS_PORT'=${{ secrets.WORDPRESS_PORT }} >> .env
          echo 'FRONTEND_APP_URL=${{ secrets.FRONTEND_APP_URL }}' >> .env

      - name: Run build
        working-directory: ./backend
        run: docker-compose up -d
